### ISSUE TITLE
Silent exit instead of error upon missing Saxon?

### ISSUE THREAD

**Issue by bmix** [nbqx/saxon-stream#1]
When creating a ```new Saxon("/path/to/saxon9he.jar")```, there seems to be no error checking for the existence of this path. Whatever I enter, it just silently quits. I use Node 0.12.2 on Windows 7.

**Comment by nbqx** [comment]
fixed. thank you for pointed out. 

https://github.com/nbqx/saxon-stream/commit/b62f4a6271368df0cb9dfc397150de1d093b2b3e
